package optaplanner.cloud_balancing;

import org.optaplanner.core.impl.domain.solution.AbstractSolution;
import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.solution.PlanningSolution
public class CloudBalancingSolution extends AbstractSolution<HardSoftScore> implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Processes")
   @org.optaplanner.core.api.domain.solution.PlanningEntityCollectionProperty
   private java.util.List<optaplanner.cloud_balancing.Process> processes;
   @org.kie.api.definition.type.Label("Computers")
   @org.optaplanner.core.api.domain.valuerange.ValueRangeProvider(id = "computers")
   private java.util.List<optaplanner.cloud_balancing.Computer> computers;

   public CloudBalancingSolution()
   {
   }

   public java.util.List<optaplanner.cloud_balancing.Process> getProcesses()
   {
      return this.processes;
   }

   public void setProcesses(
         java.util.List<optaplanner.cloud_balancing.Process> processes)
   {
      this.processes = processes;
   }

   public java.util.List<optaplanner.cloud_balancing.Computer> getComputers()
   {
      return this.computers;
   }

   public void setComputers(
         java.util.List<optaplanner.cloud_balancing.Computer> computers)
   {
      this.computers = computers;
   }

   public CloudBalancingSolution(
         java.util.List<optaplanner.cloud_balancing.Process> processes,
         java.util.List<optaplanner.cloud_balancing.Computer> computers)
   {
      this.processes = processes;
      this.computers = computers;
   }

}