package optaplanner.cloud_balancing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Process implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ID")
   private long id;
   @org.kie.api.definition.type.Label(value = "CPU")
   private int cpu;
   @org.kie.api.definition.type.Label(value = "Cost")
   private int cost;

   public Process()
   {
   }

   public long getId()
   {
      return this.id;
   }

   public void setId(long id)
   {
      this.id = id;
   }

   public int getCpu()
   {
      return this.cpu;
   }

   public void setCpu(int cpu)
   {
      this.cpu = cpu;
   }

   public int getCost()
   {
      return this.cost;
   }

   public void setCost(int cost)
   {
      this.cost = cost;
   }

   public Process(long id, int cpu, int cost)
   {
      this.id = id;
      this.cpu = cpu;
      this.cost = cost;
   }

}