package optaplanner.cloud_balancing;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class Process implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ID")
   private long id;
   @org.kie.api.definition.type.Label("Required CPU")
   private int reqCpu;

   @org.kie.api.definition.type.Label("Computer")
   @org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = { "computers" })
   private optaplanner.cloud_balancing.Computer computer;

   public Process()
   {
   }

   public long getId()
   {
      return this.id;
   }

   public void setId(long id)
   {
      this.id = id;
   }

   public int getReqCpu()
   {
      return this.reqCpu;
   }

   public void setReqCpu(int reqCpu)
   {
      this.reqCpu = reqCpu;
   }

   public optaplanner.cloud_balancing.Computer getComputer()
   {
      return this.computer;
   }

   public void setComputer(optaplanner.cloud_balancing.Computer computer)
   {
      this.computer = computer;
   }

   public Process(long id, int reqCpu,
         optaplanner.cloud_balancing.Computer computer)
   {
      this.id = id;
      this.reqCpu = reqCpu;
      this.computer = computer;
   }

}