package optaplanner.cloud_balancing;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class Process implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ID")
   private long id;
   @org.kie.api.definition.type.Label("Computer")
   @org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = { "computers" })
   private optaplanner.cloud_balancing.Computer computer;

   @org.kie.api.definition.type.Label(value = "Required CPU")
   private int requiredCpu;

   public Process()
   {
   }

   public long getId()
   {
      return this.id;
   }

   public void setId(long id)
   {
      this.id = id;
   }

   public optaplanner.cloud_balancing.Computer getComputer()
   {
      return this.computer;
   }

   public void setComputer(optaplanner.cloud_balancing.Computer computer)
   {
      this.computer = computer;
   }

   public int getRequiredCpu()
   {
      return this.requiredCpu;
   }

   public void setRequiredCpu(int requiredCpu)
   {
      this.requiredCpu = requiredCpu;
   }

   public Process(long id, optaplanner.cloud_balancing.Computer computer,
         int requiredCpu)
   {
      this.id = id;
      this.computer = computer;
      this.requiredCpu = requiredCpu;
   }

}